apiVersion: v1
kind: Service
metadata:
  name: app-one-http
  namespace: demo
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: http
  selector:
    app: app-one
  sessionAffinity: None
  type: ClusterIP