
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: argocd-server-ingress
  namespace: argocd
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/ssl-passthrough: "true"
spec:
  rules:
  - host: argocd.127.0.0.1.xip.io
    http:
      paths:
      - backend:
          serviceName: argocd-server
          servicePort: https
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: applications
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: default
  source:
    path: argo/argoapps
    repoURL: http://gitea-gitea-http.default.svc.cluster.local:3000/demo/argo-flux
    targetRevision: HEAD
  syncPolicy:
    automated:
      selfHeal: true
      prune: true